### ISSUE TITLE
Blog Content Page

### ISSUE THREAD

**Issue by KennethanCeyer** [Mighty-Legion/lull#19]
## Purpose

- As #16 story ticket, There is content page is needed to represent the detailed blog article

## TODOs

- [ ] Adjust the elements which are contained to an article page
- [ ] Add `Content` components
- [ ] Add test code
